version: '3.9'

services:
  postgresdb:
    image: postgres:latest
    container_name: postgresql-depin-db
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: admin      # Remplacez par le nom d'utilisateur souhaité
      POSTGRES_PASSWORD: adminpwd  # Remplacez par le mot de passe souhaité
      POSTGRES_DB: depindb   # Remplacez par le nom de la base de données souhaité
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d depindb"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always